---
- name: NDFC Connectivity Test
  hosts: ndfc_cisg_lab
  connection: ansible.netcommon.httpapi
  gather_facts: true

  tasks:
  #- name: GET info from NDFC
  #  cisco.dcnm.dcnm_rest:
  #    method: GET
  #    path: appcenter/cisco/ndfc/api/v1/lan-fabric/rest/interface

  - name: Query Networks
    cisco.dcnm.dcnm_network:
      fabric: netmarble-kt
      state: query
      config:
      - net_name: L4-QA-VIP
      - net_name: L4-QA-Proxy

  - name: Gather List of Fabrics from NDFC
    cisco.dcnm.dcnm_rest:
      method: GET
      path: /appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics
    register: fabrics
  
  - debug:
      var: fabrics


  - name: Delete selected networks
    cisco.dcnm.dcnm_network:
      fabric: netmarble-kt
      state: replaced
      config:
      - net_name: L4-QA-VIP
        vrf_name: QA 
        net_id: 100202
        net_template: Default_Network_Universal
        net_extension_template: Default_Network_Extension_Universal
        vlan_id: 202
        gw_ip_subnet: '10.172.30.1/24'


